### ISSUE TITLE
Game Never Loads

### ISSUE THREAD

**Issue by gudenau** [ModTheGungeon/ETGMod.Reloaded#6]
Using the latest master and the "Mod the Gungon Installer" the game never gets past the initial "Reloading..." screen.

Commit: 7aa79114ea5892e20a25f7b4cad2729bc6809089
Installer version: v17.10.19
Installer SHA-512 Hash: ea3fb0c6fb48d18484a964236c0890a3d9e23bc5d56166fbf2f9c1a62a646d02fbb7acdcd9d35a86ad644a4b61ac62b53fb3d6dd90a7677fd65c06cddb614981

Installer options:
EtG.x86_64: /home/gudenau/.local/share/Steam/steamapps/common/Enter the Gungeon/EtG.x86_64
Zip location: /home/gudenau/Desktop/ETG/ETGMod.Reloaded/build/ETGMOD.zip
Automatically show log Disabled
Close EtG... Disabled
Offline Mod Enabled
EtG.x86_64 is a wrapper... Disabled

**Comment by zatherz** [comment]
ETGMod.Installer isn't for Reloaded, use Installer.Headless (I think this was solved on Discord?)

**Comment by gudenau** [comment]
Installer.Headless did not seem to have an option to install from a zip, I must just be stupid.
